function Metrics = computeMetrics(EvaluationResults,classNames,RunFolder,GenerateROC,GenerateConfusionMatrix)



%==========================================================================
% COMPUTEMETRICS
%
% Computes fold-wise performance metrics, generates evaluation plots,
% exports fold-wise and overall results, and saves the metrics structure.
%
% INPUTS
%   EvaluationResults : Structure returned by evaluateNetwork.m
%   classNames        : Categorical class names
%
% OUTPUT
%   Metrics           : Structure containing all fold-wise metrics
%
% Generated Files
%   Results/
%      OverallMetrics.xlsx
%      Metrics.mat
%      Fold_1/
%          Metrics.xlsx
%          ClassMetrics.xlsx
%          ConfusionMatrix.png
%          ROC.png
%      ...
%==========================================================================

numFolds = numel(EvaluationResults);

Metrics = struct();



Accuracy              = zeros(numFolds,1);
Precision             = zeros(numFolds,1);
Recall                = zeros(numFolds,1);
Specificity           = zeros(numFolds,1);
F1Score               = zeros(numFolds,1);
MacroAUC              = zeros(numFolds,1);
MicroAUC              = zeros(numFolds,1);
InferenceTime         = zeros(numFolds,1);
AverageInferenceTime  = zeros(numFolds,1);

for fold = 1:numFolds

    fprintf('\n===============================================================\n');
    fprintf('Computing Metrics : Fold %d\n',fold);
    fprintf('===============================================================\n');

    TrueLabels      = EvaluationResults(fold).TrueLabels;
    PredictedLabels = EvaluationResults(fold).PredictedLabels;
    Scores          = EvaluationResults(fold).Scores;

    %% Classification metrics

    FoldMetrics = calculateMetrics( ...
    TrueLabels,...
    PredictedLabels);

    Metrics(fold).Accuracy          = FoldMetrics.Accuracy;
    Metrics(fold).Precision         = FoldMetrics.Precision;
    Metrics(fold).Recall            = FoldMetrics.Recall;
    Metrics(fold).Specificity       = FoldMetrics.Specificity;
    Metrics(fold).F1Score           = FoldMetrics.F1Score;
    
    Metrics(fold).ClassPrecision    = FoldMetrics.ClassPrecision;
    Metrics(fold).ClassRecall       = FoldMetrics.ClassRecall;
    Metrics(fold).ClassSpecificity  = FoldMetrics.ClassSpecificity;
    Metrics(fold).ClassF1           = FoldMetrics.ClassF1;
    
    Metrics(fold).ConfusionMatrix   = FoldMetrics.ConfusionMatrix;
    Metrics(fold).TotalSamples      = FoldMetrics.TotalSamples;

    %% ROC
    %% ROC (Optional)

if GenerateROC

    ROCResults = plotROC(...
        TrueLabels,...
        Scores,...
        classNames,...
        fold,...
        RunFolder);

    Metrics(fold).ClassAUC = ROCResults.ClassAUC;

else

    Metrics(fold).ClassAUC = NaN(numel(classNames),1);

end
    
    
    
    
    % Metrics(fold).MacroAUC = ROCResults.MacroAUC;
    % Metrics(fold).MicroAUC = ROCResults.MicroAUC;

    %% Confusion Matrix
%% Confusion Matrix (Optional)

if GenerateConfusionMatrix

    plotConfusionMatrix(...
        TrueLabels,...
        PredictedLabels,...
        fold,...
        RunFolder);

end

    %% Timing
    Metrics(fold).InferenceTime = EvaluationResults(fold).InferenceTime;
    Metrics(fold).AverageInferenceTime = ...
        EvaluationResults(fold).AverageInferenceTime;

    %% Store arrays
    Accuracy(fold)             = Metrics(fold).Accuracy;
    Precision(fold)            = Metrics(fold).Precision;
    Recall(fold)               = Metrics(fold).Recall;
    Specificity(fold)          = Metrics(fold).Specificity;
    F1Score(fold)              = Metrics(fold).F1Score;
    % MacroAUC(fold)             = Metrics(fold).MacroAUC;
    % MicroAUC(fold)             = Metrics(fold).MicroAUC;
    InferenceTime(fold)        = Metrics(fold).InferenceTime;
    AverageInferenceTime(fold) = Metrics(fold).AverageInferenceTime;

    %% Export fold summary
    FoldTable = table(...
        Accuracy(fold),...
        Precision(fold),...
        Recall(fold),...
        Specificity(fold),...
        F1Score(fold),...
        InferenceTime(fold),...
        AverageInferenceTime(fold),...
        'VariableNames',...
        {'Accuracy','Precision','Recall','Specificity','F1Score',...
         'InferenceTime','AverageInferenceTime'});

    foldFolder = fullfile(...
    RunFolder,...
    sprintf('Fold_%d',fold));

    if ~exist(foldFolder,'dir')
        mkdir(foldFolder);
    end

    writetable(FoldTable,fullfile(foldFolder,'Metrics.xlsx'));

    %% Export class-wise metrics
    ClassIndex = (1:numel(classNames))';

    ClassTable = table(...
        ClassIndex,...
        Metrics(fold).ClassPrecision,...
        Metrics(fold).ClassRecall,...
        Metrics(fold).ClassSpecificity,...
        Metrics(fold).ClassF1,...
        Metrics(fold).ClassAUC,...
        'VariableNames',...
        {'Class','Precision','Recall','Specificity','F1Score','AUC'});

    writetable(ClassTable,fullfile(foldFolder,'ClassMetrics.xlsx'));

end

%% Overall statistics
OverallTable = table(...
    mean(Accuracy,"omitnan"),std(Accuracy,"omitnan"),...
    mean(Precision,"omitnan"),std(Precision,"omitnan"),...
    mean(Recall,"omitnan"),std(Recall,"omitnan"),...
    mean(Specificity,"omitnan"),std(Specificity,"omitnan"),...
    mean(F1Score,"omitnan"),std(F1Score,"omitnan"),...
    mean(InferenceTime,"omitnan"),std(InferenceTime,"omitnan"),...
    mean(AverageInferenceTime,"omitnan"),...
    std(AverageInferenceTime,"omitnan"),...
    'VariableNames',...
    {'AccuracyMean','AccuracyStd',...
     'PrecisionMean','PrecisionStd',...
     'RecallMean','RecallStd',...
     'SpecificityMean','SpecificityStd',...
     'F1Mean','F1Std',...
     'InferenceTimeMean','InferenceTimeStd',...
     'AverageInferenceTimeMean','AverageInferenceTimeStd'});

writetable(OverallTable,...
    fullfile(RunFolder,'OverallMetrics.xlsx'));

MetricsOverall = OverallTable;

MetricsOverall.RunDate = datetime('now');

writetable(OverallTable,...
    fullfile(RunFolder,...
    'OverallMetrics.csv'));

save(fullfile(RunFolder,'Metrics.mat'),...
    'Metrics',...
    'MetricsOverall',...
    'Accuracy',...
    'Precision',...
    'Recall',...
    'Specificity',...
    'F1Score');

disp(' ');
disp('===============================================================');
disp('Saving ... Performance Summary');
disp('===============================================================');

FoldName = strcat("Fold_", string((1:numFolds)'));

PerformanceSummary = table(...
    FoldName,...
    string(compose("%.4f",Accuracy)),...
    string(compose("%.4f",Precision)),...
    string(compose("%.4f",Recall)),...
    string(compose("%.4f",Specificity)),...
    string(compose("%.4f",F1Score)),...
    string(compose("%.4f",InferenceTime)),...
    string(compose("%.6f",AverageInferenceTime)),...
    'VariableNames',...
    {'Fold',...
     'Accuracy',...
     'Precision',...
     'Recall',...
     'Specificity',...
     'F1Score',...
     'InferenceTime',...
     'AverageInferenceTime'});

%% -----------------------------------------------------------------------
% Add Mean ± SD Row
% -----------------------------------------------------------------------

SummaryData = [
    "Mean ± SD", ...
    string(sprintf('%.4f ± %.4f',mean(Accuracy,"omitnan"),std(Accuracy,"omitnan"))), ...
    string(sprintf('%.4f ± %.4f',mean(Precision,"omitnan"),std(Precision,"omitnan"))), ...
    string(sprintf('%.4f ± %.4f',mean(Recall,"omitnan"),std(Recall,"omitnan"))), ...
    string(sprintf('%.4f ± %.4f',mean(Specificity,"omitnan"),std(Specificity,"omitnan"))), ...
    string(sprintf('%.4f ± %.4f',mean(F1Score,"omitnan"),std(F1Score,"omitnan"))), ...
    string(sprintf('%.4f ± %.4f',mean(InferenceTime,"omitnan"),std(InferenceTime,"omitnan"))), ...
    string(sprintf('%.6f ± %.6f',mean(AverageInferenceTime,"omitnan"),std(AverageInferenceTime,"omitnan")))
    ];

SummaryRow = array2table( ...
    SummaryData,...
    'VariableNames',...
    PerformanceSummary.Properties.VariableNames);

PerformanceSummary = [PerformanceSummary; SummaryRow];

writetable(PerformanceSummary,...
    fullfile(RunFolder,...
    'PerformanceSummary.xlsx'));



disp(' ');
disp('===============================================================');
disp('Overall Performance');
disp('===============================================================');
disp(OverallTable);

fprintf('\nAverage Accuracy      : %.5f ± %.5f\n',mean(Accuracy,"omitnan"),std(Accuracy,"omitnan"));
fprintf('Average Precision     : %.5f ± %.5f\n',mean(Precision,"omitnan"),std(Precision,"omitnan"));
fprintf('Average Recall        : %.5f ± %.5f\n',mean(Recall,"omitnan"),std(Recall,"omitnan"));
fprintf('Average Specificity   : %.5f ± %.5f\n',mean(Specificity,"omitnan"),std(Specificity,"omitnan"));
fprintf('Average F1-score      : %.5f ± %.5f\n',mean(F1Score,"omitnan"),std(F1Score,"omitnan"));

disp(' ')
disp('Results saved to:')
disp(RunFolder)
disp(' ')

end
