clc
clear
close all
disp(['Execution Started : ' char(datetime('now'))])


%% ================================================================
% Create Results Folder
% ================================================================

timestamp = datestr(now,'yyyy_mm_dd_HHMMSS');

RunFolder = fullfile('Results',['Run_' timestamp]);

if ~exist(RunFolder,'dir')
    mkdir(RunFolder);
end

fprintf('\n');
disp('===============================================================')
fprintf('Results will be saved in:\n%s\n',RunFolder);
disp('===============================================================')

%% ==============================================================
% Experiment Configuration
%===============================================================

numFolds = 5;

InitialLearnRate = 0.005;

MaxEpochs = 100;

MiniBatchSize = 8;

ValidationFrequency = 6;

%% ==============================================================
% Workflow
%===============================================================

[imds,classNames,numClasses] = loadDataset();

folds = createFolds(imds,classNames,numFolds);

folds = createSplits(imds,classNames,folds);

verifySplits(imds,folds,RunFolder);

visualizeSplits(folds,classNames,RunFolder);

layers = createNetwork(numClasses);

networkSummary(layers,numClasses,RunFolder);

TrainingResults = trainNetwork(...
    imds,...
    folds,...
    layers,...
    InitialLearnRate,...
    MaxEpochs,...
    MiniBatchSize,...
    ValidationFrequency,...
    RunFolder);

plotTrainingCurves(...
    TrainingResults,...
    RunFolder);

EvaluationResults = evaluateModel( ...
    TrainingResults,...
    imds,...
    folds,...
    classNames,...
    RunFolder);

Metrics = computeMetrics(...
    EvaluationResults,...
    classNames,...
    RunFolder,...
    true,...
    true);

summarizeCrossValidation(...
    TrainingResults,...
    EvaluationResults,...
    Metrics,...
    classNames,...
    RunFolder);

analyzeDatasetComplexity(...
    imds,...
    classNames,...
    RunFolder);

RandomizationResults = randomizationTest(...
    imds,...
    folds,...
    layers,...
    classNames,...
    InitialLearnRate,...
    MaxEpochs,...
    MiniBatchSize,...
    ValidationFrequency,...
    Metrics,...
    RunFolder);


disp(['Execution Finished : ' char(datetime('now'))])